import { NextResponse } from "next/server";
import { requireCronSecret } from "@/lib/platform-guards";
import { formatMoney, getOverviewReport, getSalesReport, parseReportFilters } from "@/lib/reports";
import { sendEmail } from "@/lib/email";
import { getDeploymentInfo } from "@/lib/deployment";
import { logger } from "@/lib/logger";
import { getWeeklyDigestRecipients } from "@/lib/report-digests";

export const dynamic = "force-dynamic";

function escapeHtml(value: unknown) {
  return String(value ?? "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function digestWindow() {
  const to = new Date();
  const from = new Date(to);
  from.setDate(from.getDate() - 7);
  return { from, to };
}

function renderDigestHtml(input: {
  brandName: string;
  adminUrl: string | null;
  overview: Awaited<ReturnType<typeof getOverviewReport>>;
  sales: Awaited<ReturnType<typeof getSalesReport>>;
}) {
  const cards = [
    ["New leads", input.overview.summary.totalLeads],
    ["Reserved deals", input.sales.summary.reservations],
    ["Sold deals", input.sales.summary.soldDeals],
    ["Pipeline value", formatMoney(input.overview.summary.pipelineValue)],
  ];

  return `<!doctype html>
<html><body style="margin:0;background:#f6f7f9;font-family:Arial,sans-serif;color:#111827">
<div style="max-width:680px;margin:0 auto;padding:24px">
<h1 style="font-size:22px;margin:0 0 4px">${escapeHtml(input.brandName)} weekly sales digest</h1>
<p style="margin:0 0 20px;color:#6b7280">Asia/Tashkent weekly summary generated by the CRM.</p>
<div style="display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px">
${cards
  .map(
    ([label, value]) =>
      `<div style="background:#fff;border:1px solid #e5e7eb;border-radius:8px;padding:14px"><div style="font-size:12px;color:#6b7280">${escapeHtml(
        label
      )}</div><div style="font-size:24px;font-weight:700;margin-top:4px">${escapeHtml(value)}</div></div>`
  )
  .join("")}
</div>
<h2 style="font-size:16px;margin:24px 0 8px">Pipeline</h2>
<p style="margin:0;color:#374151">Active leads: ${escapeHtml(
    input.overview.summary.activeLeads
  )}. Overdue follow-ups: ${escapeHtml(input.overview.summary.overdueFollowups)}. Expected payments: ${escapeHtml(
    formatMoney(input.overview.summary.expectedPaymentValue)
  )}.</p>
${input.adminUrl ? `<p style="margin-top:22px"><a href="${escapeHtml(input.adminUrl)}">Open CRM reports</a></p>` : ""}
</div></body></html>`;
}

export async function POST(req: Request) {
  const cronResponse = requireCronSecret(req);
  if (cronResponse) return cronResponse;

  const deployment = getDeploymentInfo();
  const recipients = await getWeeklyDigestRecipients();
  const { from, to } = digestWindow();
  const filters = parseReportFilters(new URLSearchParams({ from: from.toISOString(), to: to.toISOString() }));
  const reportUser = { role: "owner" };
  const [overview, sales] = await Promise.all([getOverviewReport(filters, reportUser), getSalesReport(filters, reportUser)]);
  const html = renderDigestHtml({
    brandName: deployment.publicBrandName,
    adminUrl: deployment.adminUrl,
    overview,
    sales,
  });

  const delivery = await sendEmail({
    to: recipients,
    subject: `${deployment.publicBrandName} weekly sales digest`,
    html,
    text: `${deployment.publicBrandName} weekly digest: ${overview.summary.totalLeads} leads, ${sales.summary.reservations} reserved deals, ${sales.summary.soldDeals} sold deals.`,
  });

  logger.info("weekly_digest_processed", { delivery, recipientCount: recipients.length });
  return NextResponse.json({
    success: true,
    delivery,
    recipients: recipients.length,
    schedule: "Monday morning Asia/Tashkent",
  });
}
